solus_sc/changelog.py, xng/util/markdown.py
=> Autolink Differential Revisions references

repo_data/distribution.xml, repo_data/distribution.xml.in
See https://dev.getsol.us/D5035
=> Deprecate godot

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Remove mkfontdir

repo_data/distribution.xml, repo_data/distribution.xml.in
Part of [D5860](https://dev.getsol.us/D5860)
=> Drop razer-drivers due to openrazer rename

repo_data/distribution.xml, repo_data/distribution.xml.in
It is part of budgie itself nowadays :+1:
=> Send budgie-caffeine-applet down the drain

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Remove ptlib because it's not needed anymore

repo_data/distribution.xml, repo_data/distribution.xml.in
=> distribution: typo in xml-security-c-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
Part of [T7318](https://dev.getsol.us/T7318): End of Year Cleaning
=> distribution: nuke omegat-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
For: https://dev.getsol.us/D6186
More info: https://dev.getsol.us/T7770
=> repo_data: gnutls -> libgnutls-utils

eopkg_assist/backend.py, solus_sc/thirdparty.py
=> Add teamviewer in the 3rd party section

repo_data/distribution.xml, repo_data/distribution.xml.in
D7124
Signed-off-by: Joey Riches <josephriches@gmail.com>
=> Deprecate proj.4 infavour of proj rename

repo_data/distribution.xml, repo_data/distribution.xml.in
This needs to be reverted and will later the push it after I fixed the applications stack.
=> Revert the debrecation of kcalcore

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: deprecate gstreamer-1.0-plugins-bad-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: deprecate libpaper-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
[D8327](https://dev.getsol.us/D8327)
=> Deprecate pytorch-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
See [D8619](https://dev.getsol.us/D8619) Update fontforge to 20200314
=> Deprecate fontforge-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
Reference diff https://dev.getsol.us/D9092
=> Deprecate python-wikipedia

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: deprecate vcmi-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: deprecate python-pygpgme

solus_sc/updates_view.py
Fixes https://dev.getsol.us/T9466
=> Update view: Fix redundant operations when there are no updates

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: deprecate filezilla-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
See [D10145](https://dev.getsol.us/D10145).
=> Deprecate exfat-utils

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: deprecate vte2-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Add rename of 'paperwork-gui' -> 'paperwork'

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Undeprecate kodi

repo_data/distribution.xml, repo_data/distribution.xml.in
Abandoned: https://github.com/mono/monodevelop
=> Deprecate monodevelop

repo_data/distribution.xml, repo_data/distribution.xml.in
Doesn't build and no release since 2016
=> deprecate gnomint

repo_data/distribution.xml, repo_data/distribution.xml.in
Followed by https://dev.getsol.us/D13101
=> Deprecate lrzip-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
Reference task. https://dev.getsol.us/T10029
=> Deprecate fslint

repo_data/distribution.xml, repo_data/distribution.xml.in
- drop seperate wayland pkg
- drop kwayland-server which is now in kwin
- fix lapack un-deprecation
=> Changes with Plasma

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Undeprecate python-pyee

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Reintroduce clisp to enable xindy in texlive

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Undeprecate python-cssutils

repo_data/distribution.xml, repo_data/distribution.xml.in
Upstream project is dead.
https://github.com/samdroid-apps/something-for-reddit
=> Deprecate something-for-reddit

repo_data/components.xml, repo_data/components.xml.in
Resolves #199. We already have 35 packages in the repo using this component :)
=> repo_data: Add `virt` eopkg component

repo_data/distribution.xml, repo_data/distribution.xml.in
Have all been merged into one per DE
=> Deprecate old branding subpackages

repo_data/distribution.xml, repo_data/distribution.xml.in
at-spi2 now includes what these provided.
=> deprecate libatk and at-spi-atk

repo_data/distribution.xml, repo_data/distribution.xml.in
No longer generated since: https://dev.getsol.us/R3181:6b0004c00d7bde879ea2ceefea310240df1fef2b
=> repo_data: Deprecate wxPython-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
As we're actively experimenting with it atm
=> repo_data: Undeprecate packagekit

repo_data/components.xml, repo_data/components.xml.in
Related task [#234](https://github.com/getsolus/packages/issues/234)
Add missing components to SC / eopkg (T9485)
=> Add office.spelling component

repo_data/distribution.xml, repo_data/distribution.xml.in
These doc packages are not auto-generated anymore.
NO
=> No more auto-generated docs

repo_data/distribution.xml, repo_data/distribution.xml.in
Don't need 'em
[ ] Yes
< Diff URL >
=> Remove unnecessary libeconf 32bit packages

repo_data/distribution.xml, repo_data/distribution.xml.in
getsolus/packages#266
[x] Yes
getsolus/packages#363
=> Deprecate julia in favor of juliaup

repo_data/distribution.xml, repo_data/distribution.xml.in
Renamed to merkuro
[x] Yes
https://github.com/getsolus/packages/pull/388
=> repo_data: Deprecate kalendar

solus_sc/details.py
This updates the "Report license issues" link on the package details page from phabricator to the new issues.getsol.us
[x] Squashed commits with `git rebase -i` (if needed)  
[x] Built solus-sc and verified that the patch worked (if needed)
=> details: update link for reporting license issues

repo_data/distribution.xml, repo_data/distribution.xml.in
Doesn't support GNOME 45
https://github.com/getsolus/packages/commit/9cc524d42c81969beb2d2ba9f75e3c3d92d0041d
=> repo_data: Deprecate gnome-shell-extension-impatience

repo_data/distribution.xml, repo_data/distribution.xml.in
Not maintained by us
https://github.com/getsolus/packages/pull/562
=> repo_data: Deprecate libusd

repo_data/distribution.xml, repo_data/distribution.xml.in
This package hasn't been used in a long time.
=> Deprecate prelink

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Deprecate libu2f

repo_data/distribution.xml, repo_data/distribution.xml.in
Comments are self-explanatory
https://github.com/getsolus/packages/pull/866
=> quazip split and deprecate tomahawk

po/ca_ES.po
Please go the the `Preview` tab and select the appropriate sub-template:
* [Deprecation or Undeprecation](?expand=1&template=deprecation.md)
* [Other](?expand=1&template=other.md)
=> Update as ca.po

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Remove libgcrypt11

repo_data/distribution.xml, repo_data/distribution.xml.in
Split into qt5 and qt6 versions.
https://github.com/getsolus/packages/pull/1274
https://github.com/getsolus/packages/pull/1257
https://github.com/getsolus/packages/pull/1311
=> Deprecate qtkeychain unsplit

repo_data/distribution.xml, repo_data/distribution.xml.in
Bro was renamed zeek upstream.
getsolus/packages#1072
=> Repo_data: Deprecate bro

repo_data/distribution.xml, repo_data/distribution.xml.in
Orphan package. Not used by anything.
- https://github.com/getsolus/packages/pull/1323
=> repo_data: Deprecate python-argh

repo_data/distribution.xml, repo_data/distribution.xml.in
onevpl is now libvpl
https://github.com/getsolus/packages/pull/1336
=> Deprecate onevpl

repo_data/distribution.xml, repo_data/distribution.xml.in
Package was requested and merged without realising it had already been in the repository.
getsolus/packages#1424
=> repo_data: Undeprecate clustershell

repo_data/distribution.xml, repo_data/distribution.xml.in
Unmaintained, python2
https://github.com/getsolus/packages/pull/1360
=> repo_data: Deprecate sc-controller

repo_data/distribution.xml, repo_data/distribution.xml.in
Unused unmaintained
https://github.com/getsolus/packages/pull/1655
=> repo_data: Deprecate pyproject2setuppy

repo_data/distribution.xml, repo_data/distribution.xml.in
Unmaintained since 2012
https://github.com/getsolus/packages/pull/1656
=> repo_data: Deprecate gnome-doc-utils

repo_data/distribution.xml, repo_data/distribution.xml.in
Package was requested and merged without realising it had already been in the repository.
https://github.com/getsolus/packages/pull/1756
=> repo_data: Undeprecate gnome-clocks

repo_data/distribution.xml, repo_data/distribution.xml.in
Dead upstream
None
Resolves getsolus/packages/issues/2035
=> Deprecate openastro and pyswisseph

repo_data/distribution.xml, repo_data/distribution.xml.in
It's dead, Jim
https://github.com/getsolus/packages/pull/2424
=> Deprecate cups-filter-devel
