repo_data/distribution.xml, repo_data/distribution.xml.in
Removes papirus-adapta-icon-theme since it isn't part of the upstream anymore due to Adapta not being developed anymore. See [D5250](https://dev.getsol.us/D5250) for more info on the removal...
=> Remove papirus-adapta-icon-theme

repo_data/distribution.xml, repo_data/distribution.xml.in
=> repo_data: Deprecate python3-qtwebengine in favour of python-qtwebengine

repo_data/distribution.xml, repo_data/distribution.xml.in
- kcalcore gets replaced by kcalendarcore
- kpat needs old unsupported python2 stuff to be updated
=> remove kcalcore and kpat from the repo

repo_data/distribution.xml, repo_data/distribution.xml.in
As per [D7293](https://dev.getsol.us/D7293)
=> Deprecate aircrack-ng-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
sardi-icons-breeze was deprecated on version 8.2.0.
[here](https://dev.getsol.us/R2845:31c54f2e334fdfbb53dc7e2cd545e6be67d847c0) and [here](https://dev.getsol.us/R2845:31c54f2e334fdfbb53dc7e2cd545e6be67d847c0) are the patches on our developers page.
=> Deprecate sardi-icons-breeze

repo_data/distribution.xml, repo_data/distribution.xml.in
These packages are mentioned in [T5974](https://dev.getsol.us/T5974) as having issues using gtk3 version of wxwidgets.
Pgadmin is active upstream, but has not had any maintainer in the repository for two years and `youtube-dl-gui` has been dead upstream for two years.
=> Deprecate pgadmin and youtube-dl-gui

repo_data/distribution.xml, repo_data/distribution.xml.in
`gotop` is replaced with `ytop` https://dev.getsol.us/D8299
```
digikam-docs	                - docs removed here: https://dev.getsol.us/R625:d12b42ced6b8fb73db6977f89abaaf6bdde2f90d
evolution-data-server-docs	- version: 3.16.1, release: 4, but evolution-data-server is version: 3.36.3, release: 55
gexiv2-docs			- docs removed here: https://dev.getsol.us/R896:36356eb8aaaf545cf1be04902e263b55d1669d5c
gnome-builder-docs		- version: 3.22.4, release: 20, but gnome-builder is version: 3.36.0, release: 57
gnome-shell-docs		- version: 3.24.3, release: 25, but gnome-shell is version: 3.36.3, release: 59
libappindicator-docs		- docs removed here: https://dev.getsol.us/R1626:813ad172f5b4a662cb01f77ac36afd1acd1f1a57
libgxps-docs			- docs removed here: …
```
=> Deprecate gotop and some old package docs

repo_data/distribution.xml, repo_data/distribution.xml.in
- `python-chess` - Dependency needed for [LucasChess](https://dev.getsol.us/T5184), but no one stepped up to provide a patch.
- `python-envparse` - Nothing requires it. Initially was used for lbryum. 
- `python-photohash` - Dependency needed for [LucasChess](https://dev.getsol.us/T5184), but no one stepped up to provide a patch.
- `python2-pylint` - Dependency of spyder. No longer needed.
- `python-seccure` - Nothing requires it. Initially was used for lbryum.
=> Nuking some more python2 packages

repo_data/distribution.xml, repo_data/distribution.xml.in
```
python-ipython			- Python2 Packages. Was dependency of python-ipykernel. Removed here: https://dev.getsol.us/R3715:c97a3dd7d8f95eb88dcdbc6a8cd0d896402f6ba3
python-pmw and python-pymol	- Python2 packages. They aren't used by any existing packages in repository.
python-trollius			- Python2 package. It isn't used by any of existing packages in repository.
python-twodict			- Python2 package. Used to be youtube-dl-gui dependency.
```
=> Deprecate orphan python2 packages

repo_data/distribution.xml, repo_data/distribution.xml.in
See [D9241](https://dev.getsol.us/D9241)
=> Deprecate riot because of rename to element

repo_data/distribution.xml, repo_data/distribution.xml.in
Both repositories are inactive. `ruby-trollop` is replaced with `ruby-optimist`
=> Deprecate bundler and ruby-trollop

repo_data/distribution.xml, repo_data/distribution.xml.in
These are orphan python2 packages.
python2-astroid - Nothing is using it anymore
python-fastimport - Dependency of `bzr-fastimport` but this one isn't yet in repository. https://dev.getsol.us/D2937.
=> Deprecate python2-astroid and python-fastimport

repo_data/distribution.xml, repo_data/distribution.xml.in
- python-deprecation, python-node-semver, python-patch, python-pluginbase are no longer required as per deprecation of `conan`. These packages aren't used by any other packages in repository.
- python-polib and python-osinfo both are built with python2 and python3 and they are orphan packages.
I didn't find any reference why these packages are added to repo in first place. If we are going to keep these, then we just have to deprecate python2 support.
=> Deprecate python-polib, python-osinfo and conan python dependencies

repo_data/distribution.xml, repo_data/distribution.xml.in
`http-prompt` currently is broken because it requires old versions of `python-prompt-toolkit`. By doing this we have to rollback `spyder3` to v3.x.x series.
`python-parsimonious` is required only by `http-prompt`.
`httpie` is required also by `http-prompt`, but I didn't add it to this PR because I wasn't sure if it need deprecated, since originally this package wasn't added into the repo because of `http-prompt`.
=> Deprecate http-prompt

repo_data/distribution.xml, repo_data/distribution.xml.in
This is one of the best open source synthesizers available, but the develop seems to have totally lost interest in making new changes, answering comments or even merging pull requests. I see no other solution than to drop it out sadly.
=> Deprecate helm (synthesizer), no changes since 2018

repo_data/distribution.xml, repo_data/distribution.xml.in
I have patterned all files into the main package, just like we do with other header-only libraries. ETL-devel package is now obsolete.
=> Deprecate ETL-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
All these packages the release number don't match with the main packages. They are all uninstallable.
```
breeze-gtk-theme-dbginfo
CGAL-dbginfo
exfat-utils-dbginfo
finch-dbginfo
freefilesync-dbginfo
glm-dbginfo
gtk3-icon-browser-dbginfo
libcacard-dbginfo
libfakekey-dbginfo
liblouis-dbginfo
libparted-dbginfo
libpurple-dbginfo
libvala-devel-dbginfo
nettle-bin-dbginfo
nvidia-glx-driver-32bit-dbginfo
nvidia-glx-driver-dbginfo
openssh-server-dbginfo
psutils-dbginfo
soundtouch-32bit-dbginfo
soundtouch-dbginfo
tensorflow-dbginfo
the-widget-factory-3-dbginfo
unixodbc-32bit-dbginfo
unixodbc-dbginfo
vagrant-dbginfo
valadoc-dbginfo
```
`apache-maven-32bit-dbginfo` and `qgis-32bit-dbginfo` can be installed but again their release numbers don't match with the main package.
=> Remove old dbginfo packages

repo_data/distribution.xml, repo_data/distribution.xml.in
These are orphan python packages
```
python-logilab-common - From D633 dependency of pylint. Removed on D3348. Removed from pylint after 1.5.0.
(https://github.com/PyCQA/pylint/blob/pylint-2.0.1/ChangeLog#L1573)
python-base58 - Initially was required for lbry
python-backports.unittest_mock	- Required for python-keyrings.alt but it is deprecated now.
```
=> Deprecate some unnecessary python packages

repo_data/distribution.xml, repo_data/distribution.xml.in
Switching Aegisub to a fork maintained by wangqr. Update submitted [here](https://dev.getsol.us/D10281).
=> Undeprecate Aegisub

repo_data/distribution.xml, repo_data/distribution.xml.in
Deprecate dcadec as nothing uses it and this project was [merged into FFmpeg in 2016](https://github.com/foo86/dcadec/blob/master/README.md).
=> Deprecate dcadec

repo_data/distribution.xml, repo_data/distribution.xml.in
Deprecate libkate-docs.
Reference: https://dev.getsol.us/D10659
=> Deprecate libkate-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
Replaced by `intel-compute-runtime`.
=> Deprecate beignet

repo_data/distribution.xml, repo_data/distribution.xml.in
`pygtksourceview` was a dependency for `cherrytree` but now it doesn't need it.
`python-subprocess32` was a dependency for `matplotlib` which now is built with python3.
=> Deprecate python-subprocess32 and pygtksourceview

solus_sc/changelog.py
Currently the Software Center changelogs make no difference between different indentation levels (unlike our dev tracker), which can make it look a bit disorderly at times.
This PR fixes this by adding a tab for every level of indentation.
**As an example the Gnome Control Center changelog:**
**Before:**
**After:**
=> Conserve changelog bullet point indentation

repo_data/distribution.xml, repo_data/distribution.xml.in
Think I did this right.
klavaro-devel no longer exists. https://dev.getsol.us/D10867
The old gtkdatabox is no longer shipping as an internal library. https://sourceforge.net/p/klavaro/code/HEAD/tree/trunk/ChangeLog
=> Deprecate klavaro-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
They are both python2 packages.
`python-argparse` initially was a dep for `python-adapt-parser`, but not needed anymore.
About `pygoocanvas` didn't find any package that is using it, or why it was packaged at first place.
=> Deprecate python-argparse and python-qt5

repo_data/distribution.xml, repo_data/distribution.xml.in
Now maintainable due to presence of JDK 11 in the repository.
=> Undeprecate Kotlin

repo_data/distribution.xml, repo_data/distribution.xml.in
`python-functools32` orphan python2 package.
`mozjs38` isn't need anymore by [0ad](https://dev.getsol.us/D10988)
=> Deprecate mozjs38 and python-functools32

repo_data/distribution.xml, repo_data/distribution.xml.in
qt5-docs is being included back into the Solus repository to make Qt Creator show Qt5 examples, so let's undeprecate the package.
=> Undeprecate qt5-docs

solus_sc/util.py
Currently the Software Center prints binary byte units (KiB, MiB,...) in e.g. the Updates view, but actually calculates "regular" i.e. decimal power units (KB, MB,...)
See this discussion: https://discuss.getsol.us/d/6834-difference-between-software-center-and-terminal-update/19
This PR fixes it so that actually binary byte units are calculated. 
P.S. I've left the cutoff at "size < 1000" because 1023 KiB looks worse than 0.9 MiB in my opinion, but can adjust that if you feel the alternative is better.
=> Fix (download) size unit (KB -> KiB)

repo_data/distribution.xml, repo_data/distribution.xml.in
We forgot to deprecate `qt5-base-docs`. This package has no reason to exist anymore since `qt5-doc` includes all the Qt5 documentation.
=> Deprecate qt5-base-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
Per https://dev.getsol.us/D11096 stack.
Made the changes near the end to hopefully avoid conflict with Yako's PR.
=> Drop python2 and merge -devel to python-sip

repo_data/distribution.xml, repo_data/distribution.xml.in
As `dotnet` depends on `lttng-ust` and it was deprecated long ago, the package must be reintroduced.
=> Restoration of liblttng

repo_data/distribution.xml, repo_data/distribution.xml.in
The `coin3d` package got remove during a major clean-up, but `freecad` depends on it.
=> Restoration of coin3d

repo_data/distribution.xml, repo_data/distribution.xml.in
Because @EbonJaeger took maintainership of `neovim-qt` and it wasn't restored in SC, this PR fixes the issue.
=> Restoration of neovim-qt

repo_data/distribution.xml, repo_data/distribution.xml.in
`ilmbase` was superseeded by [`imath`](https://github.com/AcademySoftwareFoundation/Imath) starting with `openexr` version `3.0.0`.
=> Deprecation of ilmbase

repo_data/distribution.xml, repo_data/distribution.xml.in
Re-include yad into the repository. Necessary for steamtinkerlaunch. See https://dev.getsol.us/T9674
Diff for yad and steamtinkerlaunch on phab incoming.
My package doesn't create a yad-dbginfo, so I left that one out.
=> Re-inclusion of yad for steamtinkerlaunch

repo_data/distribution.xml, repo_data/distribution.xml.in
ResidualVM was merged into ScummVM as of 2.5.0, and "standalone" RVM is no longer maintained.
=> Deprecate residualvm

repo_data/distribution.xml, repo_data/distribution.xml.in
This package is no longer needed. Checked all the repository and none of the existing packages needs it.
Reference https://dev.getsol.us/D10692
=> Deprecate ijs and libuser

repo_data/distribution.xml, repo_data/distribution.xml.in
An unmaintained py2-gtk2 based package that is blocking our python-pillow update.
Our current python-pillow version is affected by multiple CVEs
The py3 fork gourmand can be requested via normal inclusion process.
See T10003.
=> Deprecate gourmet

repo_data/distribution.xml, repo_data/distribution.xml.in
Replace youtube-dl with yt-dlp
See https://dev.getsol.us/T10001
Corresponding diff on phab: https://dev.getsol.us/D12196
=> Replace youtube-dl with yt-dlp

repo_data/distribution.xml, repo_data/distribution.xml.in
`img2pdf` removed `python-pdfrw` from tests and going forward using `python-pikepdf`.
There is no new release for `pdfrw` since 18 Sep 2017.
=> Deprecate python-pdfrw

repo_data/distribution.xml, repo_data/distribution.xml.in
Reference diffs:
python-rawkit: https://dev.getsol.us/D12475
python-apscheduler: https://dev.getsol.us/R4728:4535f790223b
=> Deprecate python-apscheduler and python-rawkit

repo_data/distribution.xml, repo_data/distribution.xml.in
Undeprecate tagainijisho now that it supports Qt5 and has been re-accepted into the repository.
See https://dev.getsol.us/T10152
=> Undeprecate tagainijisho now that it supports Qt5

repo_data/distribution.xml, repo_data/distribution.xml.in
Is a new dependency for onionshare: https://dev.getsol.us/D12764
=> Undeprecate python-qrcode (D12764)

repo_data/distribution.xml, repo_data/distribution.xml.in
See https://dev.getsol.us/D12704#215747
=> Deprecate python-getkey because paperwork-shell dropped it

repo_data/distribution.xml, repo_data/distribution.xml.in
These dependencies were removed by `qutebrowser` in this patch https://dev.getsol.us/D10453.
Currently they aren't being used by any other package.
=> Deprecate python-cssutils and python-pypeg2

eopkg_assist/backend.py, solus_sc/thirdparty.py
This updates the name and URLs for the (Third Party) sublime text package to conform to the corresponding restructure in the Third Party repository: https://github.com/getsolus/3rd-party/pull/55
This will have to be committed/pushed at the same time as the Third Party repo PR to avoid confusion due to error messages on user's systems.
See also the change for help-center-docs: https://github.com/getsolus/help-center-docs/pull/294
=> Third Party: Update sublime text package name and URLs to new scheme

repo_data/distribution.xml, repo_data/distribution.xml.in
Looks like the last two people to add to this didn't actually run merged_repos.sh and instead manually modified distribution.xml. Otherwise they would have noticed that the distribution.xml.in was invalid xml...
=> Rename ovmf package to edk2-ovmf

repo_data/distribution.xml, repo_data/distribution.xml.in
This was a temporary package for solbuild to link against so it could safely handle libgit2 rebuilds. Classic chicken and egg dependency problem.
=> Deprecate libgit2solbuild

repo_data/distribution.xml, repo_data/distribution.xml.in
https://dev.getsol.us/D12586
During the ruby 3 stack upgrade `ruby-listen` was upgraded meaning `ruby_dep` ([which is abandoned](https://github.com/e2/ruby_dep/issues/39)) is no longer depended on by anything.
=> Deprecate ruby_dep

repo_data/distribution.xml, repo_data/distribution.xml.in
Relates to https://dev.getsol.us/D12984
Geary now uses gmime 3.x and we no longer need gmime 2.6 related packages
=> Remove gmime26

repo_data/distribution.xml, repo_data/distribution.xml.in
Is now included in the `arc-gtk-theme` package since this has been merged:
https://dev.getsol.us/D12929
=> Deprecate arc-plank-theme

repo_data/distribution.xml, repo_data/distribution.xml.in
Minetest switched to their own fork, and Irrlicht wasn't used by anything else in the repo.
=> Deprecate irrlicht

repo_data/distribution.xml, repo_data/distribution.xml.in
Due to a typo we accidentally deprecated the new opencascade `-devel` and `-dbginfo` packages instead of the old ones.
This fixes that (plus some automatic formatting corrections)
Discovered when trying to build `kicad`
=> Fix opencascade-ce deprecation

repo_data/distribution.xml, repo_data/distribution.xml.in
These packages no longer are used and they don't build.
=> Deprecate db4.8 and goffice0.8

repo_data/distribution.xml, repo_data/distribution.xml.in
=> Deprecate packagekit-docs as well

repo_data/distribution.xml, repo_data/distribution.xml.in
Following https://dev.getsol.us/D13127, `openjfx-8` is not required by anything and this is extremely unlikely to change. It also doesn't build anymore.
Related: https://dev.getsol.us/T10227
Related: https://dev.getsol.us/T9089
=> Deprecate JavaFX 8

repo_data/distribution.xml, repo_data/distribution.xml.in
Didn't support python 3.10 at the time of stack upgrade. Can be requested for re-inclusion again once it does.
=> Deprecate kdev-python

repo_data/distribution.xml, repo_data/distribution.xml.in
Needed again for newer Deja-Dup.
=> Undeprecate Google Python API package for Deja-Dup

repo_data/distribution.xml, repo_data/distribution.xml.in
Deprecate wxwidgets2.8
No longer needed by anything, last users were:
amule : switched to wxwidgets 3.0
perl-alien-wxwidgets : Using 2.8 config instead of 3.0? Unused and unmaintained regardless.
=> Deprecate wxwidgets2.8

repo_data/distribution.xml, repo_data/distribution.xml.in
Used to be a dependency for `opencv` https://dev.getsol.us/R2235:b8fe74a272fe6b35ce0e10418618d1f319018759
=> Deprecate eigen2

repo_data/distribution.xml
See [D13297](https://dev.getsol.us/D13297) and [T10209](https://dev.getsol.us/T10209).
This can be merged after [D13305](https://dev.getsol.us/D13305) is accepted.
=> Undeprecate lapack

solus_sc/thirdparty.py
Google has ended support, see https://support.google.com/talk/?hl=en
Corresponding PR in 3rd-party: https://github.com/getsolus/3rd-party/pull/66
Corresponding PR in help-center-docs: https://github.com/getsolus/help-center-docs/pull/312
=> Remove Google Talk plugin

repo_data/distribution.xml, repo_data/distribution.xml.in
Works again after the update to version 72
https://dev.getsol.us/R995:a9f90dc60ea6fe989009eb6649d7153778fb902e
=> Undeprecate dash-to-dock

repo_data/distribution.xml, repo_data/distribution.xml.in
See [D13389](https://dev.getsol.us/D13389).
=> Deprecate go-ipfs because of rename to kubo

repo_data/distribution.xml, repo_data/distribution.xml.in
The file that was being split into this package has been removed upstream.
Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>
=> Deprecate budgie-control-center-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
It is needed by `python-pikepdf`.
=> Undeprecate python-deprecation

repo_data/distribution.xml, repo_data/distribution.xml.in
These themes are abandoned upstream, they have no new releases for a long time.
Theme | Last update
-- | --
paper-gtk-theme | 25-May-16
vertex-gtk-theme | 28-Jan-17
evopop-gtk-theme | 2-Sep-17
adapta-gtk-theme | 2-Oct-18
gtk-theme-bluebird | 24-Nov-18
=> Deprecate old gtk themes

repo_data/distribution.xml, repo_data/distribution.xml.in
Reference commits:
Update `gnome-mpv` to [celluloid](https://dev.getsol.us/R975:9c575323da5db0139aee6c2c9ec1b1957e76ae85).
Drop `appdata-tools` from [easytag](https://dev.getsol.us/R678:9a541befce1c0b1b8d1faec6420a7bff12b2b89a).
=> Deprecate gnome-mpv and appdata-tools

repo_data/distribution.xml, repo_data/distribution.xml.in
Deprecate pkgs that don't support libnautilus-extension-4
Deprecate a few -docs subpackages
And a couple of miscellaneous packages
=> Deprecations from GNOME 43 upgrade

repo_data/distribution.xml, repo_data/distribution.xml.in
Using gi-docgen instead of gtk-docs these days.
Technically part of GNOME 43 deprecations
=> Deprecate librsvg-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
It is being discontinued by the author because of GNOME/Nautilus 43.
Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>
=> Deprecate nautilus-terminal

repo_data/distribution.xml, repo_data/distribution.xml.in
Integrated into nvidia-container-toolkit now https://dev.getsol.us/D13689
To be pushed some time after the next sync
Signed-off-by: Thomas Staudinger <Staudi.Kaos@gmail.com>
=> Deprecate nvidia-container-runtime

repo_data/distribution.xml, repo_data/distribution.xml.in
Main package is splitted to font-weather-icons-otf and font-weather-icons-ttf. There is no font-weather-icons package.
Commit [62fd8f9d1565](https://dev.getsol.us/R4094:62fd8f9d15653599129cb0b0bffc6317d3a907ef)
=> Deprecate font-weather-icons

repo_data/distribution.xml, repo_data/distribution.xml.in
This library is now vendored in upx itself (the only user of ucl). 
See [this discussion](https://dev.getsol.us/D13741#235676)
=> Deprecate ucl package

repo_data/distribution.xml, repo_data/distribution.xml.in
Signed-off-by: Algent Albrahimi <algent@protonmail.com>
=> Deprecate python-backports.entry_points_selectable and python-m2r

repo_data/distribution.xml, repo_data/distribution.xml.in
Gradience stopped using it, replacing it with an in-house solution
Corresponding package update: https://dev.getsol.us/R5621:636ca0081dd787b444b9f572b132bfaccce6ee32
=> Deprecate python-cssutils (again)

repo_data/distribution.xml, repo_data/distribution.xml.in
`python-editor` is a dep for `python-alembic` which is deprecated.
`python-idna_ssl` is not being used by anything in the repo.
=> Deprecate python-editor and python-idna_ssl

repo_data/distribution.xml, repo_data/distribution.xml.in
No longer needed by `scrot` as of this change: https://dev.getsol.us/R2864:18fe9144043a4ef6cff3bbebc894615f1fe0edc4
**Note:** `giblib` is hosted on our own infrastructure, so this can also be removed now:
https://getsol.us/sources/giblib-1.2.4.tar.gz
=> Deprecate giblib

repo_data/distribution.xml, repo_data/distribution.xml.in
Resolves https://dev.getsol.us/T10453
`puddletag` was deprecated as part of qt4 deprecation. Now this package switched to python3 and qt5.
Currently I have a working patch.
=> undeprecate puddletag

repo_data/distribution.xml, repo_data/distribution.xml.in
Those subpackages are not auto-generated anymore, so these packages can be deprecated.
=> Deprecate docs subpackages

repo_data/distribution.xml, repo_data/distribution.xml.in
`python-pysrt` has been replaced by the more actively maintained `python-srt`, which is also a dependency of `manim`.
To be merged after https://dev.getsol.us/D13754 has landed
=> Deprecate python-pysrt

repo_data/distribution.xml, repo_data/distribution.xml.in
Looks like they are not necessary anymore. Other distros like Fedora and Ubuntu have removed it since 6 years ago.
There could be more to deprecate, like:
- `gst-plugins-base`
- `gst-plugins-base-32bit` (This need to be removed from `steam` rundeps)
=> Deprecate old gst-plugins bad good and ugly

solus_update/application.py
Under some circumstances, pisi_callback can receive an error signal which isn't handled by the function.
Example debug logs: https://pastebin.com/CTExQYvn
'reload_repos()' is called once
variable 'is_updating' is set to True
'pisi_callback()' receives error signal
'invalidate_all()' won't be called
variable 'is_updating' won't reset to False
'check_update_status()' will always quit early because 'is_updating == True'
Debug logs with the fix: https://pastebin.com/LbGpBnBz
Discussion: https://discuss.getsol.us/d/827-solus-budgie-update-notification/
=> Fix: Update check breaks after pisi_callback error

solus_sc/components.py
Papirus added a HexChat icon that doesn't serve well as a general IRC icon. So simply switch to the "Polari" icon instead, which more or less maintains the old look.
Old:
New Hexchat icon:
New with Polari icon:
Note: There are a couple of other things one could improve in this part of the Software Center, but this is just a quick fix to get it to the same quality level as before :grin:
=> Fix "IRC clients" icon now that HexChat icon changed

solus_sc/installed_view.py
Otherwise removing a package and going back to the list will show the "Install" action for subsequent package detail views
See e.g. [here](https://www.reddit.com/r/SolusProject/comments/yi1o2v/software_center_bug/) for an issue report
This was the simplest way to do it without restructuring the whole install/remove process that I could find.
=> InstalledView: Keep details view in "remove only" state

repo_data/distribution.xml, repo_data/distribution.xml.in
Removed now that the subpackage is no longer auto-generated
=> Deprecate xdg-desktop-portal-docs

repo_data/distribution.xml, repo_data/distribution.xml.in
Official support was dropped at the end of 2022
Corresponding doflicky PR: https://github.com/getsolus/doflicky/pull/4
Corresponding xorg-driver-video-nouveau diff: https://dev.getsol.us/D14141
=> Deprecate Nvidia 390.xx driver series

repo_data/distribution.xml, repo_data/distribution.xml.in
Completely rewritten in flutter and renamed to yubico-authenticator by upstream. Doesn't work with yubikey-manager 5.x
=> repo_data: Deprecate yubioath-desktop

repo_data/distribution.xml, repo_data/distribution.xml.in
Will be used again with the flattening of branding packages
=> Undeprecate mate-desktop-branding main package

repo_data/distribution.xml, repo_data/distribution.xml.in
We are simplifying and using a singular branding pkg going forward
=> Undeprecate gnome-desktop-branding

repo_data/distribution.xml, repo_data/distribution.xml.in
Undeprecate Multidict as it is a dependency for the latest version of HTTPie.
=> Undeprecate python-multidict

repo_data/distribution.xml, repo_data/distribution.xml.in
The GNOME Wayland sessions are no longer experimental
=> repo_data: Deprecate gnome-session-shell-experimental

repo_data/distribution.xml, repo_data/distribution.xml.in
Result of changes in the dleyna packaging, and upstream changes.
=> Undeprecate dleyna-renderer, deprecate dleyna-connector-dbus-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
This depends on [D14217](https://dev.getsol.us/D14217).
=> repo_data: Deprecate pipewire-alsa

repo_data/distribution.xml, repo_data/distribution.xml.in
Now that things have been rebuilt against at-spi2 now, let's deprecate libatk and at-spi2 itself.
=> deprecate libatk and at-spi2

repo_data/distribution.xml, repo_data/distribution.xml.in
We're building all our haskell programs as static, starting now; to ease maintainership burden.
Here are the initial haskell deprecations from building bustle as static.
https://dev.getsol.us/D14119
=> repo_data: Initial haskell deprecations from static built bustle

repo_data/distribution.xml, repo_data/distribution.xml.in
These modules are no longer required by anything
=> repo_data: More python2 deprecations

repo_data/distribution.xml, repo_data/distribution.xml.in
No longer tests anything critical. Continued python2 deprecation
=> repo_data: Deprecate python2-pytest

repo_data/distribution.xml, repo_data/distribution.xml.in
Debug was disabled awhile back in order to fix krisp noise suppression.
https://dev.getsol.us/R628:943efe3d176e4beb1d222c2220473c0457e110d3
=> repo_date: Deprecate discord-dbginfo

.github/PULL_REQUEST_TEMPLATE/deprecation.md, .github/PULL_REQUEST_TEMPLATE/deprecation.yml, .github/PULL_REQUEST_TEMPLATE/other.md, .github/PULL_REQUEST_TEMPLATE/other.yml, .github/pull_request_template.md
This adds templates for creating a Pull Request, depending on if it is a package deprecation or undeprecation, or any other code change.
This includes template files in both .yml and .md because I didn't realize that GitHub only supports the new yaml formatting for issue template, and not pull requests. I didn't remove them in the hopes that GitHub will one day support them, and when that day comes, we won't have to do the work again.
GitHub also doesn't have a built-in way to select what template you want to use when creating the pull request, like they do for issues. Apparently, it's on the roadmap. Thus, we have to do this hacky thing with a default template that has links to use one of the other templates.
=> Add templates for pull requests

repo_data/distribution.xml, repo_data/distribution.xml.in
Many of these are part of [T2165](https://dev.getsol.us/T2165) for inclusion of `ClusterSSH` which was not resolved.
Some are deps of deprecated package `x2goserver` and for some other there is no info why they are added on first place.
=> Deprecate not used perl packages

repo_data/distribution.xml, repo_data/distribution.xml.in
This applet is now included in Budgie Desktop.
[ ] Yes
n/a
=> repo_data: Deprecate Budgie Trash Applet

repo_data/distribution.xml, repo_data/distribution.xml.in
ldc-devel has been moved to ldc, ldc has been moved to ldc-libs
[ ] Yes
[< Diff URL >](https://github.com/solus-packages/ldc/tree/ldc-1.34.0-59)
=> repo_data: Deprecate ldc-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
`python-cchardet` is no longer maintained and replaced with a fork `python-faust-cchardet`
`python-arpeggio` is no longer needed. It was a dep  `python-parver` which is already deprecated.
The changes are already made on `python-faust-cchardet` by adding `replaces` section.
=> Deprecate python-cchardet and python-arpeggio

repo_data/distribution.xml, repo_data/distribution.xml.in
Exa has been discontinued upstream and replaced by a fork called eza.
[ ] Yes
n/a
=> Deprecate exa

repo_data/distribution.xml, repo_data/distribution.xml.in
I actually _do_ need these packages for pam-32bit.
=> libeconf-32bit: Back from the dead

repo_data/distribution.xml, repo_data/distribution.xml.in
This is a dependency of  `valum` which was deprecated a long time ago.
=> Deprecate libmemcached

repo_data/distribution.xml, repo_data/distribution.xml.in
It was pointed out that this was not deprecated properly twice in Matrix chat. Once back in July (still on phab?) and again recently when GZ noticed it was in the binary repo but not the monorepo.
No
=> Deprecate jitsi

solus_sc/changelog.py
Since our new PR template for the packages repo contains html comments these might at times land in an actual commit.
This PR removes lines with comments before displaying the changelog.
Before:
After:
[x] Squashed commits with `git rebase -i` (if needed)  
[x] Built solus-sc and verified that the patch worked (if needed)
=> changelog: remove html comments (from PR template)

.github/PULL_REQUEST_TEMPLATE/deprecation.md, .github/PULL_REQUEST_TEMPLATE/other.md
_Details about what this Pull Request does_
This fixes the Markdown PR templates so that checkboxes actually appear as checkboxes.
Also change "diff" to "PR" now that everything is on GitHub.
**Before:**
**After:**
P.S. It seems to me like the yml files in that directory are unnecessary as those are only supported for issue templates, not PR templates from what I've read [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). Unless I'm misunderstanding something.
_Check all that apply_
[x] Squashed commits with `git rebase -i` (if needed)  
[x] Built solus-sc and verified that the patch worked (if needed)
=> PR template: fix formatting for checkboxes

repo_data/distribution.xml, repo_data/distribution.xml.in
Mage was originally introduced to build hugo. Hugo doesn't need it anymore.
*No*
https://github.com/getsolus/packages/pull/530
=> deprecate mage

repo_data/distribution.xml, repo_data/distribution.xml.in
No longer needed
[x] Yes
https://github.com/getsolus/packages/pull/426
=> Deprecate dhclient, libnm-legacy

repo_data/distribution.xml, repo_data/distribution.xml.in
This was a dependency for python2 python-mock
- No
https://github.com/getsolus/packages/pull/585
=> repo_data: Deprecate python-funcsigs

repo_data/distribution.xml, repo_data/distribution.xml.in
Replaced by gnome-shell-extension-appindicator which provides better overall support
[ ] Yes
https://github.com/solus-packages/gnome-shell-extension-appindicator/commit/fcde27c114a11838d7e0ac5bed77c9582f9c22b0
=> repo_data: Deprecate gnome-shell-extension-topicons-plus

repo_data/distribution.xml, repo_data/distribution.xml.in
Remnants of the Haskell stack update. These lucky packages escaped the mass deprecation because they have a mis-spelled category.
n/a
=> repo_data: remove some forgotten Haskell packages

repo_data/distribution.xml, repo_data/distribution.xml.in
We don't discriminate against libhandy or libadwaita anymore, also in this PR is deprecating amtk since it has been renamed to libgedit-amtk
=> distribution.xml.in: Make gnome-sound-recorder available again and deprecate amtk

repo_data/distribution.xml, repo_data/distribution.xml.in
Replaced by having `gnome-browser-connector` installed and extensions.gnome.org prompting to install an extension for the relevant browser. Replaced by gnome-browser-extension upstream
N/A
=> repo_data: Deprecate chrome-gnome-shell

eopkg_assist/backend.py
_Details about what this Pull Request does_
This removes one reference to the long-removed google-talk-plugin from the Third Party repo.
_Check all that apply_
=> Remove leftover reference to google-talk-plugin

repo_data/distribution.xml, repo_data/distribution.xml.in
Disabled libsplit for gtest so there is no longer a -devel package.
No
=> Deprecate gtest-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
Orphan packages. No more needed by their revdeps.
https://github.com/getsolus/packages/pull/802
=> Deprecate python-backcall and python-jinja2-time

repo_data/distribution.xml, repo_data/distribution.xml.in
[`pandoc-citeproc`](https://github.com/jgm/pandoc-citeproc) has been archived and merged into `pandoc` itself, so there's no need in keeping the package.
getsolus/packages#828
=> repo_data: deprecate pandoc-citeproc

setup.py, solus_update/application.py
_Details about what this Pull Request does_
This ensures that notifications from solus-update-checker can get the right Desktop Application Info file, since the file does not match the application ID.
That they should match is another issue, but for now, this will do.
Ref https://github.com/BuddiesOfBudgie/budgie-desktop/pull/479
Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>
_Check all that apply_
=> Add desktop-entry hint for solus-update-checker notifications

repo_data/distribution.xml, repo_data/distribution.xml.in
Orphan python packages
- python-jdcal
- python-ndg-httpsclient
- python-texttable
- python3-ezsetup
https://github.com/getsolus/packages/pull/1012
=> repo_data: Deprecate orphan python packages

repo_data/distribution.xml, repo_data/distribution.xml.in
Not used by anything in the repo
[perl-locale-maketext: Deprecate unused module](https://github.com/getsolus/packages/pull/1283)
=> repo_data: Deprecate perl-locale-maketext

repo_data/distribution.xml, repo_data/distribution.xml.in
Kwrite has been split into it's own package again to keep appstream reporting happy.
https://github.com/getsolus/packages/commit/21965ac79c3c430f727053cf542e0d8e19a5dbac
accidentally already pushed to main, will bump once this is merged.
=> repo_data: Undeprecate kwrite

repo_data/distribution.xml, repo_data/distribution.xml.in
This package is part of failed attempt to include `dvdstyler` in repo
https://github.com/getsolus/packages/pull/1390
=> repo_data: Deprecate wxsvg

repo_data/distribution.xml, repo_data/distribution.xml.in
~~Solus staff doesn't deserve this~~ Package is unmaintained since 2019
https://github.com/getsolus/packages/pull/1391
=> repo_data: Deprecate coffee

repo_data/distribution.xml, repo_data/distribution.xml.in
No more `-devel` from pandoc and wireshark
=> repo_data: Deprecate pandoc-devel and wireshark-devel

eopkg_assist/backend.py, solus_sc/thirdparty.py
This removes Skype from the Third Party section
Microsoft no longer provides updated .deb archives and recommends snap instead
See here for details: https://answers.microsoft.com/en-us/skype/forum/all/skype-for-linux-updates/da864865-d9e9-4819-8a5d-8de8934dd312
Corresponding 3rd-party PR: https://github.com/getsolus/3rd-party/pull/76
Corresponding help-center-docs PR: https://github.com/getsolus/help-center-docs/pull/469
=> Remove Skype from Third Party section

repo_data/distribution.xml, repo_data/distribution.xml.in
Package isn't supported after updating SFML to 2.6.*.
https://github.com/getsolus/packages/pull/1304
=> repo_data: Deprecate witchblast

repo_data/distribution.xml, repo_data/distribution.xml.in
Replaced by `python-pyproject-hooks`
https://github.com/getsolus/packages/pull/1507
=> repo_data: Deprecate python-pep517

repo_data/distribution.xml, repo_data/distribution.xml.in
Unmaintained upstream. Has the major disadvantage that building a kernel with it has a per-kernel-task memory penalty even when the user space tooling is not active. Other tools do not have this issue
getsolus/packages#1484
=> Deprecate latencytop

repo_data/distribution.xml, repo_data/distribution.xml.in
giblib was deprecated but the -devel package was overlooked: getsolus/solus-sc#189
This was realised by livingsilver94 when trying to install the programming.devel component resulting in
>**System error. Program terminated.
>giblib release 7 dependency of package giblib-devel is not satisfied**
< PR URL >
=> repo_data: Deprecate giblib-devel

repo_data/distribution.xml, repo_data/distribution.xml.in
It's included in the .net sdk
https://github.com/getsolus/packages/pull/1498
=> repo_data: deprecate fsharp

repo_data/distribution.xml, repo_data/distribution.xml.in
Wrongly pushed with the wrong package name, should have been python-ml-dtypes
N/A
=> repo_data: Deprecate python-ml_dtypes

repo_data/distribution.xml, repo_data/distribution.xml.in
renamed to libwebkit-gtk6 to match upstream
https://github.com/getsolus/packages/pull/1677
=> repo_data: Deprecate libwebkit-gtk5

repo_data/distribution.xml, repo_data/distribution.xml.in
We're not using it anymore
https://github.com/getsolus/packages/pull/1620
=> Deprecate bash-recovery

repo_data/distribution.xml, repo_data/distribution.xml.in
This package is unmaintained and replaced by lbreakouthd
https://github.com/getsolus/packages/pull/1844
=> Deprecate lbreakout2

repo_data/distribution.xml, repo_data/distribution.xml.in
The package source has been archived by its maintainer. Powerlevel10k has been added to the repo to take its place.
Resolves getsolus/packages/issues/1933
=> Deprecate powerlevel9k

repo_data/distribution.xml, repo_data/distribution.xml.in
They have not been updated since 2013 and no longer build. They are used for parsing flash media files, which have been long deprecated. Nothing is using these.
Resolves getsolus/packages/issues/1818
=> Deprecate libquvi and libquvi-scripts

repo_data/distribution.xml, repo_data/distribution.xml.in
Nintendo has been sending out takedown requests to places serving Yuzu code and/or packages. The Solus team doesn't want the liability, so we have decided to remove it from our repository.
n/a
=> distribution: Deprecate Yuzu

repo_data/distribution.xml, repo_data/distribution.xml.in
Archived upstream Jan '24. Doesn't build against new poppler releases.
- [] Yes
N/A
=> repo_data: Deprecate pdf2djvu

repo_data/distribution.xml, repo_data/distribution.xml.in
It was a dependency of otpclient but dropped in favor of libcotp and also been archived upstream. 
https://github.com/getsolus/packages/pull/2750
_Is this package part of the ISOs? Check common/iso_packages.txt_ and iso-tooling repository (private).
=> Deprecate libbaseencode

repo_data/distribution.xml, repo_data/distribution.xml.in
It has been archived upstream.
https://github.com/getsolus/packages/pull/2766
_Is this package part of the ISOs? Check common/iso_packages.txt_ and iso-tooling repository (private).
=> Deprecate libcroco
